name:               "knck"
decription:         "reks.io?"

url:                "//knck.github.io"
author:             "knck"
twitter:
  username:         "kknck"

baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

markdown:           kramdown

nav:
  - name:           "meta"
    href:           "//knck.github.io/meta"
  - name:           "contact"
    href:           "//knck.github.io/contact"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
