# Basic
name:               "knck.github.io"

# URL
baseurl:            "/blog"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "meta"
    href:           "//knck.github.io/blog/meta"
  - name:           "contact"
    href:           "//knck.github.io/blog/contact"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
