# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "reks.io"

# URL
baseurl:            "/blog"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "meta"
    href:           "//reks.io/blog/meta"
  - name:           "XXX"
    href:           "//github.com/knck"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
